
import django.db.models.deletion
import django.utils.timezone

from django.db import (
    migrations,
    models,
)


class Migration(
    migrations.Migration,
):

    dependencies = [
        (
            "accounts",
            "0003_authsec_rc1a_identity_metadata",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            (
                                "google",
                                "Google",
                            ),
                            (
                                "microsoft",
                                "Microsoft",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "email_at_binding",
                    models.EmailField(
                        max_length=254,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=(
                            django.utils
                            .timezone.now
                        ),
                    ),
                ),
                (
                    "last_authenticated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models
                            .deletion.CASCADE
                        ),
                        related_name=(
                            "external_identities"
                        ),
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "provider",
                            "issuer",
                            "subject",
                        ),
                        name=(
                            "acct_identity_subject_uq"
                        ),
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "provider",
                        ),
                        name=(
                            "acct_identity_user_provider_uq"
                        ),
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentityLoginGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            (
                                "google",
                                "Google",
                            ),
                            (
                                "microsoft",
                                "Microsoft",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=(
                            django.utils
                            .timezone.now
                        ),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models
                            .deletion.CASCADE
                        ),
                        related_name=(
                            "identity_login_grants"
                        ),
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "expires_at",
                        ],
                        name=(
                            "acct_grant_expires_idx"
                        ),
                    ),
                ],
            },
        ),
    ]
