import accounts.models
import django.db.models.deletion
import django.utils.timezone

from django.conf import (
    settings,
)

from django.db import (
    migrations,
    models,
)


class Migration(
    migrations.Migration,
):

    dependencies = [
        (
            "accounts",
            "0005_authsec_rc2_browser_session",
        ),
        (
            "inbox",
            "0014_h2b3d3a_registration_audit_actions",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=(
                            accounts.models
                            .generate_registration_public_id
                        ),
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            (
                                "google",
                                "Google",
                            ),
                            (
                                "microsoft",
                                "Microsoft",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "pending",
                                "Pending",
                            ),
                            (
                                "approved",
                                "Approved",
                            ),
                            (
                                "rejected",
                                "Rejected",
                            ),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "privacy_notice_version",
                    models.CharField(
                        max_length=64,
                    ),
                ),
                (
                    "terms_version",
                    models.CharField(
                        max_length=64,
                    ),
                ),
                (
                    "consent_recorded_at",
                    models.DateTimeField(),
                ),
                (
                    "requested_region",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=(
                            django.utils
                            .timezone.now
                        ),
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=(
                            django.db.models
                            .deletion.CASCADE
                        ),
                        related_name=(
                            "registration_request"
                        ),
                        to="inbox.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models
                            .deletion.SET_NULL
                        ),
                        related_name=(
                            "registration_reviews"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=(
                            django.db.models
                            .deletion.CASCADE
                        ),
                        related_name=(
                            "registration_request"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-submitted_at",
                ],
                "indexes": [
                    models.Index(
                        fields=[
                            "status",
                            "submitted_at",
                        ],
                        name=(
                            "acct_reg_status_time_idx"
                        ),
                    ),
                    models.Index(
                        fields=[
                            "provider",
                            "status",
                        ],
                        name=(
                            "acct_reg_provider_idx"
                        ),
                    ),
                ],
            },
        ),
    ]
