# Generated by Django 5.2 on 2026-06-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('approvals', '0002_approvalitem_decision_at_approvalitem_decision_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='source_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_actions', to='approvals.approvalitem'),
        ),
    ]
