# Generated by Django 5.2 on 2026-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_actionitem_source_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
