# Generated by Django 5.2 on 2026-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_actionitem_escalation_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupitem',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
