# Generated by Django 5.2 on 2026-06-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_followupitem_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('ignored', 'Ignored')], default='open', max_length=20),
        ),
    ]
