# Generated by Django 5.2 on 2026-07-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actionitem_completed_at_alter_actionitem_status'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        ('workflow', '0002_workflowinstance_workflowexecutionlog_workflowtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='source_type',
            field=models.CharField(choices=[('email', 'Email'), ('workflow', 'Workflow'), ('approval', 'Approval'), ('manual', 'Manual'), ('api', 'API'), ('ai', 'AI')], db_index=True, default='email', max_length=30),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_actions', to='workflow.workflowinstance'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='inbox.inboxmessage'),
        ),
    ]
