# Generated by Django 5.2 on 2026-08-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_aiactioncandidate'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionAnalysisState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('retry_wait', 'Retry Wait'), ('failed', 'Failed')], db_index=True, default='retry_wait', max_length=20)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_analysis_state', to='inbox.inboxmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_analysis_states', to='inbox.organization')),
            ],
        ),
    ]
