# Generated by Django 5.2 on 2026-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_aiactionanalysisstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupitem',
            name='followup_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
