# Generated by Django 5.2 on 2026-08-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_alter_followupitem_followup_due_at'),
        ('inbox', '0008_inboxmessage_followup_analyzed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('received', 'Received'), ('ignored', 'Ignored')], default='waiting', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_responses', to='inbox.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_response_items', to='inbox.organization')),
                ('resolved_by_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_expected_response_items', to='inbox.inboxmessage')),
                ('source_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_response_items', to='inbox.inboxmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_response_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
