# Generated by Django 5.2 on 2026-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_email', 'New Email'), ('reply_received', 'Reply Received'), ('send_failed', 'Send Failed'), ('send_retried', 'Send Retried'), ('send_success', 'Send Success'), ('approval_assigned', 'Approval Assigned'), ('action_assigned', 'Action Assigned'), ('overdue_action', 'Overdue Action'), ('overdue_approval', 'Overdue Approval'), ('overdue_followup', 'Overdue Follow Up'), ('system', 'System')], max_length=30),
        ),
    ]
