# Generated by Django 5.2 on 2026-07-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        ('notifications', '0003_alter_notification_type'),
        ('workflow', '0002_workflowinstance_workflowexecutionlog_workflowtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inbox.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_type',
            field=models.CharField(choices=[('workflow', 'Workflow'), ('email', 'Email'), ('system', 'System'), ('api', 'API'), ('ai', 'AI')], db_index=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflow.workflowinstance'),
        ),
        migrations.AddField(
            model_name='notification',
            name='workflow_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflow.workflownode'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
