# Generated by Django 5.2 on 2026-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalitem_decision_at_approvalitem_decision_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
