# Generated by Django 5.2 on 2026-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvalitem_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
    ]
