# Generated by Django 5.2 on 2026-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approvalitem_escalation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='action_created',
            field=models.BooleanField(default=False),
        ),
    ]
