# Generated by Django 5.2 on 2026-07-23 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_approvalitem_action_created'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        ('workflow', '0002_workflowinstance_workflowexecutionlog_workflowtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='source_type',
            field=models.CharField(choices=[('email', 'Email'), ('workflow', 'Workflow'), ('manual', 'Manual'), ('api', 'API'), ('ai', 'AI')], db_index=True, default='email', max_length=30),
        ),
        migrations.AddField(
            model_name='approvalitem',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approvals', to='workflow.workflowinstance'),
        ),
        migrations.AddField(
            model_name='approvalitem',
            name='workflow_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approvals', to='workflow.workflownode'),
        ),
        migrations.AlterField(
            model_name='approvalitem',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='inbox.conversation'),
        ),
        migrations.AlterField(
            model_name='approvalitem',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='inbox.inboxmessage'),
        ),
        migrations.AlterField(
            model_name='approvalitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
