# Generated by Django 5.2 on 2026-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_approvalitem_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
