# Generated by Django 5.2 on 2026-08-25 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_approvalitem_priority'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIApprovalCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('approver_reference', models.CharField(blank=True, max_length=500)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('evidence', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_approval_candidates', to='inbox.inboxmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_approval_candidates', to='inbox.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_approval_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'title'), name='uniq_ai_approval_candidate_message_title')],
            },
        ),
    ]
