# Generated by Django 5.2 on 2026-09-03 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_aiapprovalanalysisstate'),
        ('inbox', '0011_recipient_directory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalReviewCandidateOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_method', models.CharField(choices=[('ai', 'AI'), ('deterministic', 'Deterministic')], max_length=30)),
                ('source_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='aiapprovalcandidate',
            name='candidate_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiapprovalcandidate',
            name='extraction_method',
            field=models.CharField(choices=[('ai', 'AI'), ('deterministic', 'Deterministic')], db_index=True, default='ai', max_length=30),
        ),
        migrations.AddField(
            model_name='aiapprovalcandidate',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aiapprovalcandidate',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aiapprovalcandidate',
            name='source_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='aiapprovalcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_domain', ''), _negated=True), models.Q(('candidate_fingerprint', ''), _negated=True)), fields=('user', 'organization', 'source_domain', 'candidate_fingerprint'), name='uniq_approval_review_scope_fp'),
        ),
        migrations.AddField(
            model_name='approvalreviewcandidateoccurrence',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='approvals.aiapprovalcandidate'),
        ),
        migrations.AddField(
            model_name='approvalreviewcandidateoccurrence',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_review_candidate_occurrences', to='inbox.inboxmessage'),
        ),
        migrations.AddConstraint(
            model_name='approvalreviewcandidateoccurrence',
            constraint=models.UniqueConstraint(fields=('candidate', 'message'), name='uniq_approval_review_candidate_message'),
        ),
    ]
