# Generated by Django 5.2 on 2026-09-03 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_approvalreviewcandidateoccurrence_and_more'),
        ('inbox', '0011_recipient_directory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiapprovalcandidate',
            name='uniq_approval_review_scope_fp',
        ),
        migrations.AddConstraint(
            model_name='aiapprovalcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending_review'), models.Q(('source_domain', ''), _negated=True), models.Q(('candidate_fingerprint', ''), _negated=True)), fields=('user', 'organization', 'source_domain', 'candidate_fingerprint'), name='uniq_approval_review_scope_fp'),
        ),
    ]
