# Generated by Django 5.2 on 2026-06-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0004_businessobjectalias_businessobjectcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('DOMAIN', 'Domain'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WEBSITE', 'Website'), ('GST', 'GST'), ('PAN', 'PAN'), ('TAX', 'Tax'), ('CRM', 'CRM'), ('ERP', 'ERP'), ('CUSTOMER_ID', 'Customer ID'), ('VENDOR_ID', 'Vendor ID'), ('EMPLOYEE_ID', 'Employee ID'), ('ALIAS', 'Alias'), ('CUSTOM', 'Custom')], max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('normalized_value', models.CharField(db_index=True, max_length=500)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('teams', 'Teams'), ('slack', 'Slack'), ('api', 'API'), ('crm', 'CRM'), ('erp', 'ERP'), ('csv', 'CSV'), ('ai', 'AI'), ('discovery', 'Discovery')], default='manual', max_length=30)),
                ('lifecycle', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('SUGGESTED', 'Suggested'), ('VERIFIED', 'Verified'), ('TRUSTED', 'Trusted'), ('ARCHIVED', 'Archived')], default='DISCOVERED', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='context.businessobject')),
            ],
            options={
                'ordering': ['business_object', 'identity_type', 'value'],
                'indexes': [models.Index(fields=['identity_type', 'normalized_value'], name='knowledge_b_identit_d31ab2_idx'), models.Index(fields=['source'], name='knowledge_b_source_ed0a39_idx'), models.Index(fields=['lifecycle'], name='knowledge_b_lifecyc_5f40e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_object', 'identity_type', 'normalized_value'), name='unique_business_identity')],
            },
        ),
    ]
