# Generated by Django 5.2 on 2026-06-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_businessobjectalias_businessobjectcontact_and_more'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('GENERAL', 'General'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('APPROVAL', 'Approval'), ('PAYMENT', 'Payment'), ('QUOTE', 'Quotation'), ('CONTRACT', 'Contract'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('LEGAL', 'Legal')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('resolver_reason', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_evidence', to='context.businessobject')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_evidence', to='inbox.conversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_evidence', to='inbox.inboxmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_evidence', to='inbox.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_key', models.CharField(max_length=150)),
                ('fact_value', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_facts', to='context.businessobject')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_facts', to='inbox.organization')),
                ('primary_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='knowledge.knowledgeevidence')),
            ],
            options={
                'ordering': ['fact_key'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['organization', 'evidence_type'], name='knowledge_k_organiz_b3fefe_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['conversation'], name='knowledge_k_convers_548b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['message'], name='knowledge_k_message_f47e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['business_object'], name='knowledge_k_busines_355c17_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['created_at'], name='knowledge_k_created_276ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['is_active'], name='knowledge_k_is_acti_f89b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['organization'], name='knowledge_k_organiz_c2cb39_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['business_object'], name='knowledge_k_busines_d955bf_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['fact_key'], name='knowledge_k_fact_ke_70f156_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['status'], name='knowledge_k_status_936687_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgefact',
            constraint=models.UniqueConstraint(fields=('business_object', 'fact_key'), name='unique_business_fact'),
        ),
    ]
