# Generated by Django 5.2 on 2026-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_businessobjectalias_businessobjectcontact_and_more'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        ('knowledge', '0002_knowledgeevidence_knowledgefact_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgeevidence',
            name='knowledge_k_busines_355c17_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgeevidence',
            name='knowledge_k_is_acti_f89b0e_idx',
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='ai_provider',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='evidence_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='resolver_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgeevidence',
            name='source_channel',
            field=models.CharField(default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='knowledgefact',
            name='fact_type',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgefact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgefact',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgefact',
            name='source_channel',
            field=models.CharField(default='system', max_length=30),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['business_object', 'evidence_type'], name='knowledge_k_busines_ec9200_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['source_channel'], name='knowledge_k_source__f81b80_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['evidence_hash'], name='knowledge_k_evidenc_924c42_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['is_active', 'is_archived'], name='knowledge_k_is_acti_2c10f1_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['fact_type'], name='knowledge_k_fact_ty_98a1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgefact',
            index=models.Index(fields=['source_channel'], name='knowledge_k_source__3dd9ec_idx'),
        ),
    ]
