# Generated by Django 5.2 on 2026-07-02 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        ('knowledge', '0003_remove_knowledgeevidence_knowledge_k_busines_355c17_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('BACKFILL', 'Knowledge Backfill'), ('REINDEX', 'Knowledge Reindex'), ('IMPORT', 'Knowledge Import'), ('SYNC', 'Knowledge Sync')], max_length=30)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_jobs', to='inbox.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_type'], name='knowledge_k_job_typ_17a994_idx'), models.Index(fields=['status'], name='knowledge_k_status_aec833_idx'), models.Index(fields=['started_at'], name='knowledge_k_started_25f46b_idx')],
            },
        ),
    ]
