# Generated by Django 5.2 on 2026-07-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0007_person'),
        ('knowledge', '0004_knowledgejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeevidence',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_evidence', to='context.person'),
        ),
    ]
