"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# ==================================================
# Deployment Security
# ==================================================
#
# Development remains unchanged by default.
# Production deployments must explicitly enable
# secure transport/cookie settings through environment
# variables.
#

SECURE_SSL_REDIRECT = os.environ.get(
    "DJANGO_SECURE_SSL_REDIRECT",
    "false",
).lower() in (
    "1",
    "true",
    "yes",
)

SESSION_COOKIE_SECURE = os.environ.get(
    "DJANGO_SESSION_COOKIE_SECURE",
    "false",
).lower() in (
    "1",
    "true",
    "yes",
)

CSRF_COOKIE_SECURE = os.environ.get(
    "DJANGO_CSRF_COOKIE_SECURE",
    "false",
).lower() in (
    "1",
    "true",
    "yes",
)

SECURE_HSTS_SECONDS = int(
    os.environ.get(
        "DJANGO_SECURE_HSTS_SECONDS",
        "0",
    )
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get(
        "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
        "false",
    ).lower()
    in (
        "1",
        "true",
        "yes",
    )
)

SECURE_HSTS_PRELOAD = os.environ.get(
    "DJANGO_SECURE_HSTS_PRELOAD",
    "false",
).lower() in (
    "1",
    "true",
    "yes",
)

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'actions',
    'approvals',
    'timeline',
    'corsheaders',
    'context',
    'knowledge',
    'rest_framework',
    'drf_spectacular',
    'accounts',
    'email_accounts',
    'workflow.apps.WorkflowConfig',
    'conversations',
    'inbox',
    'audit_logs',
    'oauth_tokens',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # must be first
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "platform_core.context.middleware.RequestContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = os.environ.get(
    "CORS_ALLOW_ALL_ORIGINS",
    "true" if DEBUG else "false",
).lower() in ("1", "true", "yes")

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


BASE_DIR = Path(__file__).resolve().parent.parent

# ==================================================
# Database Configuration
# ==================================================
#
# SQLite remains the default for local development.
#
# Pilot / production environments can explicitly
# enable PostgreSQL with:
#
# DJANGO_DB_ENGINE=postgresql
#
# and the DB_* environment variables below.
#

DB_ENGINE = os.environ.get(
    "DJANGO_DB_ENGINE",
    "sqlite",
).strip().lower()


if DB_ENGINE in {
    "postgres",
    "postgresql",
}:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ["DB_USER"],
            "PASSWORD": os.environ["DB_PASSWORD"],
            "HOST": os.environ.get(
                "DB_HOST",
                "127.0.0.1",
            ),
            "PORT": os.environ.get(
                "DB_PORT",
                "5432",
            ),
            "CONN_MAX_AGE": int(
                os.environ.get(
                    "DB_CONN_MAX_AGE",
                    "60",
                )
            ),
        }
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#OAuth Tokens
'oauth_tokens',
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

AUTH_USER_MODEL = 'accounts.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# GOOGLE OAUTH

GOOGLE_CLIENT_ID = os.environ["GOOGLE_CLIENT_ID"]

GOOGLE_CLIENT_SECRET = os.environ["GOOGLE_CLIENT_SECRET"]

GOOGLE_REDIRECT_URI = os.environ.get(
    "GOOGLE_REDIRECT_URI",
    "http://127.0.0.1:8000/api/google/oauth/callback/",
)

# MICROSOFT OAUTH

MICROSOFT_CLIENT_ID = os.environ["MICROSOFT_CLIENT_ID"]

MICROSOFT_CLIENT_SECRET = os.environ["MICROSOFT_CLIENT_SECRET"]

MICROSOFT_TENANT_ID = os.environ["MICROSOFT_TENANT_ID"]

MICROSOFT_REDIRECT_URI = os.environ.get(
    "MICROSOFT_REDIRECT_URI",
    "http://localhost:8000/api/microsoft/oauth/callback/",
)

# ===============================
# Redis / Celery Configuration
# ===============================

REDIS_URL = os.environ.get(
    "REDIS_URL",
    "redis://127.0.0.1:6379/0",
)

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TASK_ALWAYS_EAGER = False

CELERY_WORKER_POOL = os.environ.get(
    "CELERY_WORKER_POOL",
    "solo",
)


INSTALLED_APPS += ["django_celery_beat"]
INSTALLED_APPS += ["notifications"]
INSTALLED_APPS += ["search"]


from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": os.environ.get("DRF_USER_THROTTLE_RATE", "1000/hour"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Unified Communication Hub API",
    "DESCRIPTION": "Inbox, Attachments, Policies, Audit & Auth APIs",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SECURITY": [{"bearerAuth": []}],
}

# =========================
# Razorpay (Payment Gateway)
# =========================

RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID", "rzp_test_dummy")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET", "dummy_secret")


CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = "Asia/Kolkata"


ASGI_APPLICATION = "backend.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}
# Required for websocket auth
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

import redis

REDIS_CLIENT = redis.Redis.from_url(
    REDIS_URL,
    decode_responses=True,
)

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "sync-all-email-accounts": {
        "task": "inbox.tasks.periodic_sync_all_users",
        "schedule": crontab(minute="*/5"),
    },

    "refresh-expired-oauth-tokens": {
        "task": "oauth_tokens.tasks.refresh_expired_tokens",
        "schedule": crontab(minute="*/10"),
    },

    "analyze-new-messages": {
        "task": "actions.tasks.analyze_new_messages",
        "schedule": crontab(minute="2-57/5"),
    },

    "analyze-new-approvals": {
        "task": "approvals.tasks.analyze_new_approvals",
        "schedule": crontab(minute="3-58/5"),
    },

    "analyze-new-followups": {
        "task": "actions.followup_tasks.analyze_new_followups",
        "schedule": crontab(minute="4-59/5"),
    },

    "analyze-new-expected-responses": {
        "task": "actions.expected_response_tasks.analyze_new_expected_responses",
        "schedule": crontab(minute="5-59/5"),
    },

    "scan-overdue-work-every-hour": {
        "task": "notifications.tasks.scan_overdue_work_and_notify",
        "schedule": crontab(minute=0),
    },

    "escalation-engine": {
        "task": "notifications.tasks_escalation.run_escalation_engine",
        "schedule": 3600,
    },
}

# ==================================================
# Knowledge Engine
# ==================================================

KNOWLEDGE_JOB_CHECKPOINT_INTERVAL = 25

# ==================================================
# Enterprise Logging
# ==================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "enterprise": {
            "format": (
                "%(asctime)s | "
                "%(levelname)s | "
                "%(name)s | "
                "%(message)s"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "enterprise",
        },
    },
    "loggers": {
        "knowledge": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ------------------------------------------------------------
# One UCH AI / Action Intelligence
# ------------------------------------------------------------

ONEUCH_AI_PROVIDER = os.getenv(
    "ONEUCH_AI_PROVIDER",
    "mock",
)

ONEUCH_AI_MODE = os.getenv(
    "ONEUCH_AI_MODE",
    "cloud",
).strip().lower()

ONEUCH_AI_MODEL = os.getenv(
    "ONEUCH_AI_MODEL",
    "gpt-5.6-luna",
)

ONEUCH_AI_TIMEOUT_SECONDS = float(
    os.getenv(
        "ONEUCH_AI_TIMEOUT_SECONDS",
        "30",
    )
)

ACTION_AI_ENABLED = (
    os.getenv(
        "ACTION_AI_ENABLED",
        "false",
    ).lower()
    in {"1", "true", "yes", "on"}
)

ACTION_AI_AUTO_CREATE_THRESHOLD = int(
    os.getenv(
        "ACTION_AI_AUTO_CREATE_THRESHOLD",
        "90",
    )
)

ACTION_AI_REVIEW_THRESHOLD = int(
    os.getenv(
        "ACTION_AI_REVIEW_THRESHOLD",
        "75",
    )
)

ACTION_AI_MAX_ATTEMPTS = int(
    os.getenv(
        "ACTION_AI_MAX_ATTEMPTS",
        "3",
    )
)

ACTION_AI_RETRY_BASE_SECONDS = int(
    os.getenv(
        "ACTION_AI_RETRY_BASE_SECONDS",
        "300",
    )
)

ACTION_AI_RETRY_MAX_SECONDS = int(
    os.getenv(
        "ACTION_AI_RETRY_MAX_SECONDS",
        "3600",
    )
)

ACTION_AI_ALLOWED_ACCOUNT_IDS = {
    int(value.strip())
    for value in os.getenv(
        "ACTION_AI_ALLOWED_ACCOUNT_IDS",
        "",
    ).split(",")
    if value.strip().isdigit()
}

APPROVAL_AI_ENABLED = (
    os.getenv(
        "APPROVAL_AI_ENABLED",
        "false",
    ).lower()
    == "true"
)

APPROVAL_AI_AUTO_CREATE_THRESHOLD = int(
    os.getenv(
        "APPROVAL_AI_AUTO_CREATE_THRESHOLD",
        "95",
    )
)

APPROVAL_AI_REVIEW_THRESHOLD = int(
    os.getenv(
        "APPROVAL_AI_REVIEW_THRESHOLD",
        "85",
    )
)

APPROVAL_AI_MAX_ATTEMPTS = int(
    os.getenv(
        "APPROVAL_AI_MAX_ATTEMPTS",
        "3",
    )
)

APPROVAL_AI_RETRY_BASE_SECONDS = int(
    os.getenv(
        "APPROVAL_AI_RETRY_BASE_SECONDS",
        "300",
    )
)

APPROVAL_AI_RETRY_MAX_SECONDS = int(
    os.getenv(
        "APPROVAL_AI_RETRY_MAX_SECONDS",
        "3600",
    )
)

APPROVAL_AI_ALLOWED_ACCOUNT_IDS = {
    int(value.strip())
    for value in os.getenv(
        "APPROVAL_AI_ALLOWED_ACCOUNT_IDS",
        "",
    ).split(",")
    if value.strip().isdigit()
}