# Generated by Django 5.2 on 2026-01-02 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('fetch_mail', 'Fetch Mail'), ('send_mail', 'Send Mail'), ('read_message', 'Read Message'), ('attachment_upload', 'Attachment Upload'), ('credential_expired', 'Credential Expired'), ('error', 'System Error')], max_length=50)),
                ('platform', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'IMAP'), ('teams', 'Microsoft Teams'), ('system', 'System')], max_length=20)),
                ('description', models.TextField(help_text='Human readable log message')),
                ('metadata', models.JSONField(blank=True, help_text='Optional structured data (no message content)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
