# Generated by Django 5.2 on 2026-03-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('account_type', models.CharField(choices=[('imap', 'IMAP / POP3'), ('gmail', 'Gmail (OAuth)'), ('outlook', 'Outlook / Microsoft 365')], max_length=20)),
                ('smtp_password', models.CharField(blank=True, help_text='App password for SMTP (temporary, Phase 1 only)', max_length=255, null=True)),
                ('last_synced_uids', models.JSONField(blank=True, default=dict, help_text='Last synced IMAP UID for incremental sync')),
                ('imap_server', models.CharField(blank=True, max_length=255, null=True)),
                ('imap_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('credential_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('reauth_required', 'Re-authentication Required')], default='reauth_required', max_length=20)),
                ('credential_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
