"""
Enterprise Human Review Contracts.

These contracts represent immutable review requests
created after AI Governance determines that a human
must approve or reject an AI recommendation.

These are runtime objects only.

Persistence is intentionally handled elsewhere
(Approval Center, Action Center, etc.).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from typing import Dict
from typing import Optional
from uuid import uuid4


# ---------------------------------------------------------
# Human Review Request
# ---------------------------------------------------------


@dataclass(frozen=True)
class AIHumanReviewRequest:
    """
    Immutable review request generated by AI Governance.
    """

    review_id: str = field(
        default_factory=lambda: str(uuid4())
    )

    workflow_instance_id: Optional[str] = None

    workflow_node_id: Optional[str] = None

    governance_outcome: str = "REVIEW"

    confidence: float = 0.0

    policy_name: str = "default"

    reason: str = ""

    response_type: str = "text"

    ai_output: Any = None

    review_type: str = "AI_GOVERNANCE"

    status: str = "PENDING"

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    created_at: datetime = field(
        default_factory=datetime.utcnow
    )

    @property
    def requires_review(self) -> bool:
        return True

    def serialize(self) -> dict:

        return {
            "review_id": self.review_id,
            "workflow_instance_id":
                self.workflow_instance_id,
            "workflow_node_id":
                self.workflow_node_id,
            "governance_outcome":
                self.governance_outcome,
            "confidence":
                self.confidence,
            "policy_name":
                self.policy_name,
            "reason":
                self.reason,
            "response_type":
                self.response_type,
            "ai_output":
                self.ai_output,
            "metadata":
                dict(self.metadata),
            "created_at":
                self.created_at.isoformat(),
            "requires_review":
                True,
            "review_type": self.review_type,
            "status": self.status,
        }


# ---------------------------------------------------------
# Human Review Decision
# ---------------------------------------------------------


@dataclass(frozen=True)
class AIHumanReviewDecision:
    """
    Immutable human review outcome.

    Produced after an authorized reviewer
    approves or rejects an AI recommendation.
    """

    review_id: str

    approved: bool

    reviewer: Optional[str] = None

    comments: str = ""

    decided_at: datetime = field(
        default_factory=datetime.utcnow
    )

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    @property
    def rejected(self) -> bool:

        return not self.approved

    def serialize(self) -> dict:

        return {
            "review_id":
                self.review_id,
            "approved":
                self.approved,
            "rejected":
                self.rejected,
            "reviewer":
                self.reviewer,
            "comments":
                self.comments,
            "decided_at":
                self.decided_at.isoformat(),
            "metadata":
                dict(self.metadata),
        }