# Generated by Django 5.2 on 2026-03-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='search_index',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
