# Generated by Django 5.2 on 2026-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_conversation_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_key',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
