# Generated by Django 5.2 on 2026-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_conversation_conversation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_preview',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20),
        ),
    ]
