# Generated by Django 5.2 on 2026-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_conversation_last_message_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='attachment_meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
