# Generated by Django 5.2 on 2026-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_inboxmessage_attachment_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='action_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
