# Generated by Django 5.2 on 2026-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_inboxmessage_action_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='approval_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
