# Generated by Django 5.2 on 2026-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_inboxmessage_approval_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='followup_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
