# Generated by Django 5.2 on 2026-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_inboxmessage_followup_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='expected_response_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
