from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "inbox",
            "0010_inboxmessage_recipient_meta_sender_meta",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipientDirectoryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_indexed_message_id",
                    models.PositiveBigIntegerField(
                        default=0,
                    ),
                ),
                (
                    "indexed_message_count",
                    models.PositiveBigIntegerField(
                        default=0,
                    ),
                ),
                (
                    "last_indexed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "recipient_directory_states"
                        ),
                        to="inbox.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "recipient_directory_states"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipientContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                    ),
                ),
                (
                    "normalized_email",
                    models.CharField(
                        max_length=254,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "received_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "to_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "cc_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "bcc_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "reply_to_count",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name="recipient_contacts",
                        to="inbox.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name="recipient_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-sent_count",
                    "-message_count",
                    "-last_seen_at",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recipientdirectorystate",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "organization",
                ),
                name="uniq_rcpt_state_user_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipientcontact",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "organization",
                    "normalized_email",
                ),
                name="uniq_rcpt_user_org_email",
            ),
        ),
        migrations.AddIndex(
            model_name="recipientcontact",
            index=models.Index(
                fields=[
                    "user",
                    "normalized_email",
                ],
                name="inbox_rcpt_uemail_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipientcontact",
            index=models.Index(
                fields=[
                    "user",
                    "last_seen_at",
                ],
                name="inbox_rcpt_useen_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipientcontact",
            index=models.Index(
                fields=[
                    "organization",
                    "normalized_email",
                ],
                name="inbox_rcpt_oemail_idx",
            ),
        ),
    ]
