# Generated by Django 5.2 on 2026-06-26 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('inbox', '0007_inboxmessage_approval_analyzed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessobjecttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businessobjecttype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='businessobjecttype',
            name='color',
            field=models.CharField(default='#2563EB', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('priority', models.IntegerField(default=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='context.businessobjecttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objects', to='inbox.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('relationship', models.CharField(default='related', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='context.businessobject')),
            ],
        ),
        migrations.AddIndex(
            model_name='businessobject',
            index=models.Index(fields=['organization'], name='context_bus_organiz_b47d16_idx'),
        ),
        migrations.AddIndex(
            model_name='businessobject',
            index=models.Index(fields=['name'], name='context_bus_name_0dfb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessobject',
            index=models.Index(fields=['status'], name='context_bus_status_883922_idx'),
        ),
        migrations.AddIndex(
            model_name='businessobjectlink',
            index=models.Index(fields=['content_type'], name='context_bus_content_744dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='businessobjectlink',
            index=models.Index(fields=['object_id'], name='context_bus_object__660c83_idx'),
        ),
    ]
