# Generated by Django 5.2 on 2026-06-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_remove_businessobjecttype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessobject',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_objects', to='context.businessobjecttype'),
        ),
    ]
