# Generated by Django 5.2 on 2026-06-27 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_alter_businessobject_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessObjectAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='context.businessobject')),
            ],
            options={
                'ordering': ['alias'],
                'unique_together': {('business_object', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='BusinessObjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='context.businessobject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business_object', 'email')},
            },
        ),
        migrations.CreateModel(
            name='BusinessObjectDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='context.businessobject')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('business_object', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='BusinessObjectIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('customer_id', 'Customer ID'), ('vendor_id', 'Vendor ID'), ('contract_id', 'Contract ID'), ('crm_id', 'CRM ID'), ('erp_id', 'ERP ID'), ('gst', 'GST'), ('pan', 'PAN'), ('other', 'Other')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='context.businessobject')),
            ],
            options={
                'unique_together': {('business_object', 'identifier_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='BusinessObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#2563EB', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='context.businessobject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business_object', 'name')},
            },
        ),
    ]
