# Generated by Django 5.2 on 2026-07-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_businessobjectalias_businessobjectcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('RELATED_TO', 'Related To'), ('WORKS_FOR', 'Works For'), ('EMPLOYED_BY', 'Employed By'), ('CUSTOMER_OF', 'Customer Of'), ('VENDOR_OF', 'Vendor Of'), ('PARTNER_OF', 'Partner Of'), ('OWNS', 'Owns'), ('MANAGES', 'Manages'), ('REPORTS_TO', 'Reports To'), ('MEMBER_OF', 'Member Of'), ('SUPPLIER_OF', 'Supplier Of'), ('PARENT_OF', 'Parent Of'), ('CHILD_OF', 'Child Of'), ('CONTRACT_WITH', 'Contract With'), ('PROJECT_FOR', 'Project For'), ('ATTENDED', 'Attended'), ('APPROVED_BY', 'Approved By'), ('ASSIGNED_TO', 'Assigned To')], default='RELATED_TO', max_length=50)),
                ('direction', models.CharField(choices=[('OUTGOING', 'Outgoing'), ('INCOMING', 'Incoming'), ('BIDIRECTIONAL', 'Bidirectional')], default='BIDIRECTIONAL', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(default='resolver', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='context.businessobject')),
                ('target_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='context.businessobject')),
            ],
            options={
                'ordering': ['-confidence', '-updated_at'],
                'indexes': [models.Index(fields=['relationship_type'], name='context_bus_relatio_2141e3_idx'), models.Index(fields=['source_object'], name='context_bus_source__bf3336_idx'), models.Index(fields=['target_object'], name='context_bus_target__546b31_idx'), models.Index(fields=['confidence'], name='context_bus_confide_887213_idx'), models.Index(fields=['direction'], name='context_bus_directi_8cd077_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_object', 'target_object', 'relationship_type'), name='unique_business_relationship')],
            },
        ),
    ]
