# Generated by Django 5.2 on 2026-07-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_businessrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrelationship',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
