# Generated by Django 5.2 on 2026-06-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0007_inboxmessage_approval_analyzed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('message_received', 'Message Received'), ('action_created', 'Action Created'), ('action_completed', 'Action Completed'), ('approval_created', 'Approval Created'), ('approval_approved', 'Approval Approved'), ('approval_rejected', 'Approval Rejected'), ('followup_created', 'Follow Up Created'), ('followup_completed', 'Follow Up Completed'), ('notification_sent', 'Notification Sent'), ('escalated', 'Escalated')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='inbox.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
