# Generated by Django 5.2 on 2026-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
