# Generated by Django 5.2 on 2026-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowinstance_workflowexecutionlog_workflowtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtoken',
            name='wait_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflowtoken',
            name='wait_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowtoken',
            name='wait_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
