# Generated by Django 5.2 on 2026-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowtoken_wait_configuration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'ordering': ['priority', 'id']},
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers are evaluated first.'),
        ),
    ]
