# Generated by Django 5.2 on 2026-08-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflowtransition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='parent_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_instances', to='workflow.workflowinstance'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='parent_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_instances', to='workflow.workflowtoken'),
        ),
    ]
