# Generated by Django 5.2 on 2026-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_workflowinstance_parent_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('action', 'Action'), ('approval', 'Approval'), ('ai', 'AI'), ('condition', 'Condition'), ('wait', 'Wait'), ('notification', 'Notification'), ('webhook', 'Webhook'), ('script', 'Script'), ('subworkflow', 'Sub Workflow'), ('fork', 'Fork'), ('join', 'Join')], max_length=30),
        ),
    ]
