# Generated by Django 5.2 on 2026-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_workflownode_node_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowexecutionlog',
            options={'ordering': ['sequence_number', 'created_at', 'id']},
        ),
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='event_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='previous_event_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='sequence_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workflowexecutionlog',
            index=models.Index(fields=['instance', 'sequence_number'], name='workflow_exec_instance_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowexecutionlog',
            constraint=models.UniqueConstraint(fields=('instance', 'sequence_number'), name='unique_execution_event_sequence'),
        ),
    ]
